// Mocks generated by Mockito 5.4.5 from annotations
// in matchpoint/test/place_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:geolocator/geolocator.dart' as _i4;
import 'package:matchpoint/models/category.dart' as _i5;
import 'package:matchpoint/services/place.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [PlaceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlaceService extends _i1.Mock implements _i2.PlaceService {
  MockPlaceService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Map<String, dynamic>> fetchNearbyPlaces(
    _i4.Position? pos,
    _i5.SportsCategories? cat, {
    String? searchName,
    int? radius = 20000,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchNearbyPlaces,
              [pos, cat],
              {#searchName: searchName, #radius: radius, #limit: limit},
            ),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> fetchNearbyPlacesNextPage(
    String? nextPageUrl,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchNearbyPlacesNextPage, [nextPageUrl]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);
}
